{{ if .Values.ranchervm.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ranchervm-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ranchervm-role
subjects:
  - kind: ServiceAccount
    name: ranchervm-service-account
    namespace: ranchervm-system
{{ end }}
