
# prebuilt users
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user1
    namespace: hobbyfarm
spec:
    email: user1
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user2
    namespace: hobbyfarm
spec:
    email: user2
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user3
    namespace: hobbyfarm
spec:
    email: user3
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user4
    namespace: hobbyfarm
spec:
    email: user4
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user5
    namespace: hobbyfarm
spec:
    email: user5
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user6
    namespace: hobbyfarm
spec:
    email: user6
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user7
    namespace: hobbyfarm
spec:
    email: user7
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user8
    namespace: hobbyfarm
spec:
    email: user8
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user9
    namespace: hobbyfarm
spec:
    email: user9
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user10
    namespace: hobbyfarm
spec:
    email: user10
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user11
    namespace: hobbyfarm
spec:
    email: user11
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user12
    namespace: hobbyfarm
spec:
    email: user12
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user13
    namespace: hobbyfarm
spec:
    email: user13
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user14
    namespace: hobbyfarm
spec:
    email: user14
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user15
    namespace: hobbyfarm
spec:
    email: user15
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user16
    namespace: hobbyfarm
spec:
    email: user16
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user17
    namespace: hobbyfarm
spec:
    email: user17
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user18
    namespace: hobbyfarm
spec:
    email: user18
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user19
    namespace: hobbyfarm
spec:
    email: user19
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
---
apiVersion: hobbyfarm.io/v2
kind: User
metadata:
    name: user20
    namespace: hobbyfarm
spec:
    email: user20
    password: '$2a$10$QkpisIWlrq/uA/BWcOX0/uYWinHcbbtbPMomY6tp3Gals0LbuFEDO'
    access_codes:
    - workshop
    settings:
      bashbrawl_enabled: "true"
      ctr_enabled: "true"
      ctxAccessCode: example-access-code
      terminal_fontSize: "14"
      terminal_theme: GitHub
      theme: light
