---
{{ if $.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shell
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ $.Values.ingress.hostnames.shell }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: shell
                port:
                  number: 80
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.Values.ingress.hostnames.shell | quote }}
      {{- if hasKey .Values.ingress.tls.secrets "shell" }}
      secretName: {{ $.Values.ingress.tls.secrets.shell }}
      {{- end }}
  {{- end }}
{{ end }}
