{{ if .Values.terraform.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-controller
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: terraform-controller
{{ end }}
