{{ if $.Values.guac }}
---
apiVersion: v1
kind: Service
metadata:
  name: guacd
spec:
  selector:
    component: guacd
  type: ClusterIP
  ports:
    - name: tcp
      port: 4822
      targetPort: 4822
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: guac
spec:
  selector:
    component: guac
  ports:
    - name: http
      port: 80
      targetPort: 4567
{{ end }}
